name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - compiler: gcc
          # - compiler: clang
          # - compiler: gcc
          #   debug_flag: "--enable-debug"
          # - compiler: clang
          #   debug_flag: "--enable-debug"
          - compiler: gcc
            slim_check_nd: "yes"
          # - compiler: clang
          #   slim_check_nd: "yes"
    env:
      DEBUG_FLAG: ${{ matrix.debug_flag }}
      slim_CHECK_ND: ${{ matrix.slim_check_nd }}
      CC: ${{ matrix.compiler }}
      LMNTAL_HOME: ${{ github.workspace }}/lmntal-compiler
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt -qq update
    - run: sudo apt install -y ant re2c
    - run: git clone https://github.com/lmntal/lmntal-compiler.git
    - run: cd lmntal-compiler && ant compile && cd ..
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure $DEBUG_FLAG
    - name: make
      run: make
    - name: make check
      run: make check
